// Generated by Wrangler on Sat May 18 2024 10:37:00 GMT-0400 (Atlantic Standard Time)
interface Env {
	ENVIRONMENT: "development";
	ASTEROID_API: "http://localhost:8080/v1/graphql";
	ASTEROID_API_WSS: "ws://localhost:8080/v1/graphql";
	TX_EXPLORER: "http://localhost:1316/cosmos/tx/v1beta1/txs/";
	RPC: "http://localhost:16657";
	REST: "http://localhost:1316";
	CHAIN_ID: "gaialocal-1";
	CHAIN_NAME: "localcosmoshub";
	MAX_FILE_SIZE: "550000";
	GAS_PRICE: "0.005uatom";
	USE_IBC: "false";
	USE_EXTENSION_DATA: "true";
	MAINTENANCE_MODE: "false";
	NEUTRON_CHAIN_ID: "test-1";
	NEUTRON_CHAIN_NAME: "localneutron";
	NEUTRON_BRIDGE_CONTRACT: "neutron1vlqvaptpe7hztjj52whxk5mm6k2ey9hu4rv5ueu89shagk72mewq6jnxez";
	BRIDGE_ENDPOINTS: "http://localhost:8080/v1/graphql,http://localhost:8080/v1/graphql";
	ASTROPORT_FACTORY_CONTRACT: "neutron1hptk0k5kng7hjy35vmh009qd5m6l33609nypgf2yc6nqnewduqasxplt4e";
}
