// Generated by Wrangler on Wed Mar 20 2024 12:00:53 GMT+0100 (Central European Standard Time)
interface Env {
	ENVIRONMENT: "development";
	ASTEROID_API: "http://localhost:8080/v1/graphql";
	ASTEROID_API_WSS: "ws://localhost:8080/v1/graphql";
	TX_EXPLORER: "http://localhost:1316/cosmos/tx/v1beta1/txs/";
	RPC: "http://localhost:16657";
	REST: "http://localhost:1316";
	CHAIN_ID: "gaialocal-1";
	CHAIN_NAME: "localcosmoshub";
	MAX_FILE_SIZE: "550000";
	GAS_PRICE: "0.005uatom";
	USE_IBC: "false";
	USE_EXTENSION_DATA: "true";
	MAINTENANCE_MODE: "false";
}
