// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: string;
	ASTEROID_API: string;
	ASTEROID_API_WSS: string;
	TX_EXPLORER: string;
	RPC: string;
	REST: string;
	CHAIN_ID: string;
	CHAIN_NAME: string;
	MAX_FILE_SIZE: string;
	GAS_PRICE: string;
	USE_IBC: string;
	USE_EXTENSION_DATA: string;
	MAINTENANCE_MODE: string;
	UPLOAD_API: string;
	MINTER_ADDRESS: string;
	ASSETS_URL: string;
	ASTEROID_URL: string;
}
