/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export interface InstantiateMsg {
  bridge_chain_id: string
  bridge_ibc_channel: string
  ibc_timeout_seconds: number
  owner: string
  signer_threshold: number
}
export type ExecuteMsg =
  | {
      link_token: {
        signatures: string[]
        source_chain_id: string
        token: TokenMetadata
      }
    }
  | {
      enable_token: {
        ticker: string
      }
    }
  | {
      disable_token: {
        ticker: string
      }
    }
  | {
      receive: {
        amount: Uint128
        destination_addr: string
        signatures: string[]
        source_chain_id: string
        ticker: string
        transaction_hash: string
      }
    }
  | {
      send: {
        destination_addr: string
      }
    }
  | {
      retry_send: {
        failure_id: number
      }
    }
  | {
      add_signer: {
        name: string
        public_key_base64: string
      }
    }
  | {
      remove_signer: {
        public_key_base64: string
      }
    }
  | {
      update_config: {
        bridge_chain_id?: string | null
        bridge_ibc_channel?: string | null
        ibc_timeout_seconds?: number | null
        signer_threshold?: number | null
      }
    }
  | {
      propose_new_owner: {
        expires_in: number
        owner: string
      }
    }
  | {
      drop_ownership_proposal: {}
    }
  | {
      claim_ownership: {}
    }
export type Uint128 = string
export interface TokenMetadata {
  decimals: number
  image_url: string
  name: string
  ticker: string
}
export type QueryMsg =
  | {
      config: {}
    }
  | {
      signers: {}
    }
  | {
      tokens: {
        limit?: number | null
        start_after?: string | null
      }
    }
  | {
      token: {
        ticker: string
      }
    }
  | {
      disabled_tokens: {
        limit?: number | null
        start_after?: string | null
      }
    }
export type Addr = string
export interface Config {
  bridge_chain_id: string
  bridge_ibc_channel: string
  ibc_timeout_seconds: number
  owner: Addr
  signer_threshold: number
}
export interface QueryTokensResponse {
  tokens: string[]
}
export interface QuerySignersResponse {
  signers: [string, string][]
}
export interface QueryTokenResponse {
  denom?: string | null
}
