/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */
import * as _1 from './AsteroidNeutronBridge.client.js'
import * as _0 from './AsteroidNeutronBridge.types.js'

export namespace contracts {
  export const AsteroidNeutronBridge = {
    ..._0,
    ..._1,
  }
}

export * from './AsteroidNeutronBridge.client.js'
export * from './AsteroidNeutronBridge.types.js'
