// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: inscription.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inscription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentType       string `protobuf:"bytes,1,opt,name=parent_type,json=parentType,proto3" json:"parent_type,omitempty"`
	ParentIdentifier string `protobuf:"bytes,2,opt,name=parent_identifier,json=parentIdentifier,proto3" json:"parent_identifier,omitempty"`
	Metadata         []byte `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content          []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Inscription) Reset() {
	*x = Inscription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inscription_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Inscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inscription) ProtoMessage() {}

func (x *Inscription) ProtoReflect() protoreflect.Message {
	mi := &file_inscription_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inscription.ProtoReflect.Descriptor instead.
func (*Inscription) Descriptor() ([]byte, []int) {
	return file_inscription_proto_rawDescGZIP(), []int{0}
}

func (x *Inscription) GetParentType() string {
	if x != nil {
		return x.ParentType
	}
	return ""
}

func (x *Inscription) GetParentIdentifier() string {
	if x != nil {
		return x.ParentIdentifier
	}
	return ""
}

func (x *Inscription) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Inscription) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_inscription_proto protoreflect.FileDescriptor

var file_inscription_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x73, 0x74, 0x65, 0x72, 0x6f, 0x69, 0x64, 0x22, 0x91, 0x01,
	0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x6f, 0x6e, 0x6f, 0x76, 0x61, 0x6e, 0x73, 0x6f, 0x6c, 0x6d, 0x73, 0x2f, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x2d, 0x69, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x72, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_inscription_proto_rawDescOnce sync.Once
	file_inscription_proto_rawDescData = file_inscription_proto_rawDesc
)

func file_inscription_proto_rawDescGZIP() []byte {
	file_inscription_proto_rawDescOnce.Do(func() {
		file_inscription_proto_rawDescData = protoimpl.X.CompressGZIP(file_inscription_proto_rawDescData)
	})
	return file_inscription_proto_rawDescData
}

var file_inscription_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_inscription_proto_goTypes = []interface{}{
	(*Inscription)(nil), // 0: asteroid.Inscription
}
var file_inscription_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inscription_proto_init() }
func file_inscription_proto_init() {
	if File_inscription_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inscription_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Inscription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inscription_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inscription_proto_goTypes,
		DependencyIndexes: file_inscription_proto_depIdxs,
		MessageInfos:      file_inscription_proto_msgTypes,
	}.Build()
	File_inscription_proto = out.File
	file_inscription_proto_rawDesc = nil
	file_inscription_proto_goTypes = nil
	file_inscription_proto_depIdxs = nil
}
